name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'typeddjango/django-stubs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel

      - name: Build package
        run: |
          python setup.py --version
          python setup.py sdist bdist_wheel
          twine check dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

          print_hash: true
          verify_metadata: false  # check done above

      - name: create release
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = context.ref.replace(/^refs\/tags\//, '');
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: `Release ${tagName.replace(/^v/, '')}`,
            });

            if (release.status < 200 || release.status >= 300) {
              core.setFailed(`Could not create release for tag '${tagName}'`);
              return;
            }
